from dataclasses import dataclass
from typing import Protocol, Callable, Any
from qcax_fabric_contracts import PluginDescriptor, EventSpec
class PluginContextProtocol(Protocol):
    plugin_id:str
    def provide(self, capability_id:str, implementation:Any): ...
    def service(self, capability_id:str)->Any: ...
    def effect(self, disposer:Callable[[],Any], description:str): ...
    def on(self, spec:EventSpec, handler:Callable[...,Any], priority:int=0): ...
    def dispatch(self, spec:EventSpec, payload:Any): ...
@dataclass(frozen=True)
class PluginDefinition:
    descriptor:PluginDescriptor
    on_mount:Callable[[PluginContextProtocol],Any]|None=None
    on_unmount:Callable[[PluginContextProtocol],Any]|None=None
